### ISSUE TITLE
initial config does not properly respect AWS Auth stack

### ISSUE THREAD

**Issue by smiller171** [flightlesscom/lambda-serverless-send-email#1]
Amazon has an auth stack set up that is extremely useful, but this app's config doesn't respect it. It asks me to enter my API keys even though I already have a config file and `AWS_PROFILE` var set

**Comment by ned-kelly** [comment]
Hi smiller171,
The original project was written with Serverless 0.5 which is now very old...

It's now been rewritten with Serverless 1.x, Docker Containerisation (for local development/testing) and AWS Profile support.

Thanks for mentioning, I'll close this issue as it's now been resolved as of: https://github.com/david-nedved/lambda-serverless-send-email/tree/v1.0
